import React, { useContext } from 'react';
import { Menu, SubMenu, Item } from 'burger-menu';
import AppContext from '../context/AppProvider';
import Image from '../Image';
import Logo from '../../assets/brand/logo.jpeg';
import Icon from '../Icon';
import Button from '../Button';

const BurgerMenu = () => {
	const { setOpenMenu, openMenu, darkMode, handleDarkMode } = useContext(AppContext);

	const closeMenu = () => {
		setOpenMenu(false);
	};

	const renderIcon = () => {
		if (!darkMode) return <Icon className='fa-regular fa-sun-bright icon-theme' onClick={handleDarkMode} />;

		return <Icon className='fa-light fa-moon icon-theme' onClick={handleDarkMode} />;
	};

	return (
		<Menu className='BurgerMenu' isOpen={openMenu} onClose={closeMenu} side='left'>
			<div className='BurgerMenu-head'>
				<div className='BurgerMenu-logo'>
					<Image alt='logo' src={Logo} className='BurgerMenu-image' />
					<Button className='BurgerMenu-theme'>{renderIcon()}</Button>
				</div>
				<Icon className='fa-solid fa-xmark BurgerMenu-close' onClick={closeMenu} />
			</div>
			<Item itemKey={'introduction'} text={'Introduction'} />
			<SubMenu title='Getting Started'>
				<Item itemKey={'installation'} text={'Installation'} />
				<Item itemKey={'configuration'} text={'Configuration'} />
				<Item itemKey={'playground'} text={'Playground'} />
				<Item itemKey={'typeScript'} text={'TypeScript Support'} />
			</SubMenu>
			<SubMenu title='Guides' selectedKey=''>
				<Item itemKey={'pages'} text={'Pages'} />
				<SubMenu title='Docs'>
					<Item itemKey={'create'} text={'Create a doc'} />
					<SubMenu title='Sidebar'>
						<Item itemKey={'sidebar'} text={'Sidebar items'} />
						<Item itemKey={'autogenerated'} text={'Autogenerated'} />
						<Item itemKey={'multiple'} text={'Using multiple sidebars'} />
					</SubMenu>
					<Item itemKey={'create'} text={'Create a doc'} />
					<Item itemKey={'versioning'} text={'Versioning'} />
					<Item itemKey={'docs'} text={'Docs Multi-instance'} />
				</SubMenu>
				<Item itemKey={'blog'} text={'Blog'} />
				<SubMenu title='Markdown Features'>
					<Item itemKey={'features'} text={'Markdown Features'} />
				</SubMenu>
				<Item itemKey={'layout'} text={'Styling and Layout'} />
				<Item itemKey={'swizzling'} text={'Swizzling'} />
				<Item itemKey={'assets'} text={'Static Assets'} />
				<Item itemKey={'search'} text={'Search'} />
				<Item itemKey={'support'} text={'Browser support'} />
				<Item itemKey={'seo'} text={'SEO'} />
				<Item itemKey={'plugins'} text={'Using Plugins'} />
				<Item itemKey={'deployment'} text={'Deployment'} />
				<Item itemKey={'internationalization'} text={'Internationalization'} />
				<Item itemKey={'next'} text={"What's Next?"} />
			</SubMenu>
			<SubMenu title='Advance Guides'>
				<Item itemKey={'notice'} text={'Announcement'} />
				<Item itemKey={'union'} text={'Union Inquiries'} />
				<Item itemKey={'entry'} text={'Entry information'} />
			</SubMenu>
			<SubMenu title='Migrating from v1 to v2'>
				<Item itemKey={'notice'} text={'Announcement'} />
				<Item itemKey={'union'} text={'Union Inquiries'} />
				<Item itemKey={'entry'} text={'Entry information'} />
			</SubMenu>
		</Menu>
	);
};

export default BurgerMenu;
